DROP TABLE STUDENTS;

CREATE TABLE STUDENTS(
    STUDENT_NUMBER    VARCHAR2(20),
    PASSWORD   		  VARCHAR2(30),
    STUDENT_NAME      VARCHAR2(50),
    CELL_PHONE   	  VARCHAR2(20),
    EMAIL        	  VARCHAR2(50),
    ADDRESS      	  VARCHAR2(200),
    GRADE             NUMBER,
    ADMISSION_YEAR    DATE,
    GRADUATION_YEAR   DATE,
    MAJOR 			  VARCHAR2(50),
    INTRODUCTION 	  VARCHAR2(200),
    REG_DATE     	  DATE DEFAULT SYSDATE,
    UPDATE_DATE  	  DATE DEFAULT SYSDATE,
    PRIMARY KEY(STUDENT_NUMBER)
);
/*
INSERT INTO MEMBERS 
VALUES('sjjo0319', '1234', 'seojin', '010-3045-0339', 'sjjo0319@naver.com', '서울시 노원구', 1, SYSDATE, SYSDATE);

INSERT INTO MEMBERS 
VALUES('duohui12','111111','정다혜','010-3656-7418','duohui12@gmail.com','서울시 광진구 구의동 영화사로 11길',1,sysdate,sysdate);

INSERT INTO MEMBERS(USER_ID, PASSWORD, USER_NAME, CELL_PHONE, EMAIL, ADDRESS, GRADE)
VALUES('ahra','1234','아라','010-2061-0602','ahra@gmail.com','대구',1);
*/

SELECT * FROM STUDENTS;

DELETE FROM STUDENTS
WHERE USER_ID = 'ahra';

DROP TABLE AVATARS;

CREATE TABLE AVATARS(
	STUDENT_NUMBER VARCHAR2(20) PRIMARY KEY,
	IMAGE BLOB
);

SELECT * FROM AVATARS;

CREATE TABLE BOARDS (
	BOARD_ID 	NUMBER PRIMARY KEY,
	TITLE 		VARCHAR2(256) NOT NULL,
	WRITER 		VARCHAR2(20) NOT NULL,
	READ_CNT	NUMBER,
	CONTENT 	CLOB,
	REG_DATE 	DATE,
	UPDATE_DATE DATE
);
ALTER TABLE BOARDS
ADD(WRITER_NAME VARCHAR(50));

UPDATE BOARDS
SET WRITER_NAME='admin'
WHERE WRITER='admin';

CREATE SEQUENCE BOARDS_SEQ;

INSERT INTO BOARDS(BOARD_ID, TITLE, WRITER, READ_CNT, CONTENT, REG_DATE, UPDATE_DATE)
VALUES(BOARDS_SEQ.NEXTVAL,'안녕하세요','20132570', 0,'날씨가 너무 덥네요..',sysdate, sysdate);

CREATE TABLE ATTACHMENTS(
     ATTACHMENT_ID	 NUMBER PRIMARY KEY,
     FILE_NAME 		 VARCHAR2(256),
     LOCATION		 VARCHAR2(1024),
     BOARD_ID		 NUMBER,
     REG_DATE 		 DATE,
     CONSTRAINT F_ATTACHMENTS_BOARD FOREIGN KEY(BOARD_ID)
     REFERENCES BOARDS(BOARD_ID)
);

CREATE SEQUENCE ATTACHMENTS_SEQ;

SELECT * FROM ATTACHMENTS;

DROP TABLE REPLIES;

CREATE TABLE REPLIES( 
	REPLY_ID NUMBER PRIMARY KEY, 
	BOARD_ID NUMBER NOT NULL, 
	REPLY_LEVEL NUMBER, 
	PARENT NUMBER, 
	WRITER VARCHAR2(20) NOT NULL, 
	CONTENT VARCHAR2(1024), 
	DELETED NUMBER(1), 
	LIKE_CNT NUMBER,
	REG_DATE DATE, 
	UPDATE_DATE DATE, 
	CONSTRAINT F_REPLIES_BOARD FOREIGN KEY(BOARD_ID) REFERENCES BOARDS(BOARD_ID) ON DELETE CASCADE, 
	CONSTRAINT F_REPLIES_STUDENT FOREIGN KEY(WRITER) REFERENCES STUDENTS(STUDENT_NUMBER) ON DELETE SET NULL
);

SELECT * FROM REPLIES;

CREATE SEQUENCE REPLIES_SEQ;